exit value is 1 if all connection to servers fail
zopefoundation/ZEO pull request #215
Opened 2022-10-03 21:16 UTC by sblondon

closes: #214

This PR changes the `zeopack` exit value to 1 when all connections to server are a failure. Currently, `zeopack` outputs `Couldn't connect to: xxx` and exits with 0. I think it should be an error exit value than a succes. 

The usecase is described in #214. This PR implements  the solution **a** (as defined in issue #214) because the [`usage`](https://github.com/zopefoundation/ZEO/blob/83730901e5d7bcb0916d5391f5907e5f9d3a32e7/src/ZEO/scripts/zeopack.py#L12) constant documents `zeopack` as `Pack one or more storages hosted by ZEO servers`.

2022-10-04 14:09 UTC, dataflake requested changes
Please change the error message as suggested to make the problem more obvious.

2022-10-04 14:09 UTC, dataflake commented on src/ZEO/scripts/zeopack.py
> +        error("No servers found.")
```suggestion
        error("Cannot connect to any of the configured ZEO servers.")
```

2022-10-04 14:34 UTC, dataflake commented
Don't forget to fix the failing tests. There were some looking for the specific output generated by the old code. They are all failing now.

2022-10-05 03:55 UTC, sblondon commented
@dataflake thank for the review. The tests are fixed now.

2022-10-05 13:30 UTC, dataflake approved these changes

2022-10-05 19:21 UTC, merged

2022-10-07 05:54 UTC, icemac commented
Should there be a message in the change log or is this change merely internally?

2022-10-07 12:35 UTC, dataflake commented
I added an entry in https://github.com/zopefoundation/ZEO/commit/a6072ecd2aceb004187fdd718b8f1c3c64ffa0e6